language: node_js
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
before_script:
  - sudo service mongodb stop
  - sudo echo "replSet = set0" >> /etc/mongodb.conf
  - sudo service mongodb restart
  - sleep 15
  - mongo oplog-transform-tail-test --eval 'rs.initiate()'
  - sleep 15
