language: node_js
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
before_script:
  - sudo service mongodb stop
  - echo "replSet = set0" | sudo tee -a /etc/mongodb.conf
  - sudo service mongodb restart
  - sleep 20
  - mongo oplog-transform-tail-test --eval 'rs.initiate()'
  - sleep 15
